import { useRouter } from 'next/router';
import Head from 'next/head';

const CourseHome = () => {
   const router = useRouter();
   const id = router.query.id;

  return (
    <>  
        <Head>
            <title>{id}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
            <h1>Welcome to Next.js Query: {id}</h1>
        </div>
    </>
  );
}

export default CourseHome;