import Head from 'next/head';
import Link from 'next/link';
import styles from '@/styles/Home.module.css';
import Banner from '@/components/banner';

export default function Home() {
  const handleOnBannerBtnClick = () => {
    console.log("Banner button clicked");
  };

  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner 
          buttonText="View stores nearby" 
          handleOnClick={handleOnBannerBtnClick}
        />
        <div>
          <Link href="/coffee-store/123">Coffee Store</Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>&#169;2019 The Coffee Connoisseur</p>
      </footer>
    </>
  );
}
