import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.card}>
          <h1 className={styles.title}>Coffee Connoisseur</h1>
          <p className={styles.description}>  
            Find the best coffee shops in your area
          </p>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>&#169;2019 The SocialBooking</p>
      </footer>
    </>
  )
}
