import Head from 'next/head';
import styles from '@/styles/home.module.css';
import Banner from '@/components/banner';
import Image from 'next/image';
import CardList from '@/components/cardList';

const cardInfo = [
  {
    id: 1,
    href: "/coffee-store/Dark-Horse-Coffee",
    imageUrl: "/static/CoffeeShop1.jpeg",
    name: "Dark Horse Coffee",
    details:"Great Coffee Shop hidden away in the Gulch of Nashville!"
  },
  {
    id: 2,
    href: "/coffee-store/C-Jacks-Coffee",
    imageUrl: '/static/CoffeeShop1.jpeg',
    name: "C Jacks Coffee",
    details:"Great Coffee Shop hidden away in Midtown of Nashville!"

  },
  {
    id: 3,
    href: "/coffee-store/D Frazier Coffee",
    imageUrl: "/static/CoffeeShop1.jpeg",
    name: "D Frazier Coffee",
    details:"Great Coffee Shop hidden away in Germantown Nashville!"
  },
  {
    id: 4,
    href: "/coffee-store/J-Long-Coffee",
    imageUrl: '/static/CoffeeShop1.jpeg',
    name: "J Long Coffee",
    details:"Great Coffee Shop hidden away in East Nashville!"
  }
];

export default function Home() {
  const handleOnBannerBtnClick = () => {
    console.log("Banner button clicked");
  };

  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner 
          buttonText="View stores nearby" 
          handleOnClick={handleOnBannerBtnClick}
        />
       
        <div className={styles.heroImage}>
          <Image 
            src="/static/bannerImage.png"
            width={350}
            height={350}
            alt="Coffee Image"
          />
        </div>
        
        <CardList
          cardData={cardInfo}
        />

      </main>

      <footer className={styles.footer}>
        <p>&#169;2019 The Coffee Connoisseur</p>
      </footer>
    </>
  );
}
