export const robots = [
    {
        id:1,
        imgUrl:'https://robohash.org/test?200x200',
        name:'Price',
        email:'price@robots.com'
    },
    {
        id:2,
        imgUrl:'https://robohash.org/test1',
        name:'Doug',
        email:'doug@robots.com'
    },
    {
        id:3,
        imgUrl:'https://robohash.org/test2',
        name:'Jake',
        email:'jake@robots.com'
    },
    {
        id:4,
        imgUrl:'https://robohash.org/test3',
        name:'Garrett',
        email:'garrett@robots.com'
    },
    {
        id:5,
        imgUrl:'https://robohash.org/test4',
        name:'Chris',
        email:'chris@robots.com'
    }
];