import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export default function CourseHome() {
    const router = useRouter();
    const webRoute = router.route;
  return (
    <>
        <Head>
            <title>{webRoute}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
            <h1>Welcome to Next.js</h1>
        </div>
    </>
  );
}